### PR TITLE
sysbench-mongodb benchmark test image 

### LINKED ISSUE #24: Create a sysbench-mongodb test container to perform mongdb benchmarks with OpenEBS storage
If you’re not familiar with sysbench, it’s a great project developed by Alexey Kopytov that lets you run different types of benchmarks (referred to as “tests” by the tool), including database benchmarks. The database tests are implemented in Lua scripts, which means you can customize them as needed (or even write new ones from scratch) – something useful for simulating specific workloads.

PerconaLab has tweaked sysbench to integrate mongodb support. We need to containerize this to be readily available to be used as part of a Kubernetes Job to perform mongodb benchmarks.

### PR DESCRIPTION
**Pull request by ksatchit**
Code-Changes : 
----------------
- Included a sysbench benchmark client image with mongo-db integration. 
- This image will enable running oltp lua scripts on mongodb containers

Notes : 
-------
The oltp test can be invoked while running this test container using command below : 

```
./sysbench/sysbench --mongo-write-concern=1 --mongo-url="mongodb://10.44.0.3" --mongo-database-name=sbtest --test=./sysbench/tests/mongodb/oltp.lua --oltp_table_size=100 --oltp_tables_count=10 --num-threads=10 --rand-type=pareto --report-interval=10 --max-requests=0 --max-time=600 --oltp-point-selects=10 --oltp-simple-ranges=1 --oltp-sum-ranges=1 --oltp-order-ranges=1 --oltp-distinct-ranges=1 --oltp-index-updates=1 --oltp-non-index-updates=1 --oltp-inserts=1 run
```

This PR fixes #24 

Tested On : 
------------
Container tested after building locally on ubuntu 16.04 64 bit Baremetal boxes/ESX VM

### CODE REVIEW

**Comment by yudaykiran** [comment]
The travis build is failing, is that alright? I don't think it is creating the image in docker hub.

**Comment by ksatchit** [comment]
Right. Debugging this now. I see that the custom-percona image has failed to build - and we haven't got to the new sysbench image (the makefile triggers a build of *all* images in the repo - maybe we need to relook this as well)

**Comment by ksatchit** [comment]
Here is an update on this : 

The earlier failure was due to a "now unavailable" mysql-server package in the mysql repo for debian jessie that was being referenced in mysql-master and mysql-slave images. Updated from 5.7.19-1debian8 to 5.7.20-1debian8.

The current failure is  on the sysbench-mongo image. The same dockerfile is seen to work on a local ubuntu setup. Trying to identify the issue

**Comment by ksatchit** [comment]
The failure to build the sysbench-mongodb image was due to the presence of a git-sub module in the build context. It has been replaced with a normal directory.

**Pull request merged**
